### ISSUE TITLE
Pressing Return / 13 should not submit the form

### ISSUE THREAD

**Issue by fabianmu** [amsify42/jquery.amsify.suggestags#21]
I have an input, working with `amsifySuggestags` within a `<form>`, however when I press **return** (13) the form is being submitted. Instead the Tag should be added.

![2019-09-23 at 14 51](https://user-images.githubusercontent.com/89517/65426969-a379f580-de11-11e9-99c2-b2e6250bd84b.gif)

A jsfiddle can be found here:
https://jsfiddle.net/mnLv517y/5/

Any idea what's causing this?

**Comment by lievcin** [comment]
+ 1

**Comment by amsify42** [comment]
This is the default behavior of form with input in it.
You can also press key **188** that is **Comma** or do this
```html
<form onkeypress="return event.keyCode != 13;">
```
or control it using jquery
```JS
$("form").keypress(function(event){
	return event.keyCode != 13; 
});
```

**Comment by bug-z** [comment]
Actually I think this should be fixed in Plugin itself. 

Pressing Return is the expected way to add tag. Also, Comma won't work with many languages, f.e. on my Cyrillic keyboard if English I have letter 'Б' on Comma button too. And in Cyrillic mode Comma is Shift + Question Mark Button (and it doesn't add tag).

So Comma solution is not a solution for many languages. And it's not the expected way anyway.

Quick fix is adding to script

```
$('.amsify-suggestags-input').keypress(function(e) {
            if (e.keyCode == 13) {
                return false;
            }
});
```
Author can surely this event handler to Plugin code as it is Plugin-specific handler.

**Comment by amsify42** [comment]
Thanks for providing the fix. I have added this, pushed and published.
